spring.application.name=vty

## Database Connection ##
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://darphane.corsoicnq4bk.eu-west-1.rds.amazonaws.com:5432/vty_project
spring.datasource.username=vty_project
spring.datasource.password=QlHl0GR5bv6VcRX7
spring.jpa.hibernate.ddl-auto=update